### ISSUE TITLE
Link to publication?

### ISSUE THREAD

**Issue by cthoyt** [labsyspharm/DRIADrc#3]
hey @ArtemSokolov, great to see you've got a repo for your figures.

Do these go with an upcoming publication, something on a pre-print server, or something already past peer review? I'd love to check this article out. Putting a link if there's something available would be great.

**Comment by ArtemSokolov** [comment]
Hi @cthoyt. We're gearing up for a submission. I'll be sure to add a link to the paper once it becomes available.

**Comment by ArtemSokolov** [comment]
A pre-print is currently available at https://www.biorxiv.org/content/10.1101/2020.05.15.098749v1
